{
 "title": "Dockers",
 "time": { "from": "now-2h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "docker",
    "label": "docker",
    "query": "select distinct(container_name) from docker_container_cpu"
   }
  ]
 },
 "panels": [
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(\"time\",$__interval),\n  avg(usage_percent) AS \"cpu\",\n  container_name as docker\nFROM docker_container_cpu\nWHERE\n  $__timeFilter(\"time\") AND\n  container_name in($docker)\nGROUP BY time, container_name\nORDER BY time ASC"
    }
   ]
  },
  {
   "title": "MEM",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "rawSql": "SELECT\n  \"time\" AS \"time\",\n  avg(usage_percent) AS \"mem\",\n  container_name as docker\nFROM docker_container_mem\nWHERE\n  $__timeFilter(\"time\") AND container_name in($docker)\nGROUP BY time, container_name\nORDER BY time ASC\n"
    }
   ]
  },
  {
   "title": "NET",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "rawSql": "SELECT\n  \"time\" AS \"time\",\n  avg(tx_bytes) - lag(avg(tx_bytes)) OVER (PARTITION BY container_name ORDER BY \"time\") AS \"tx_bytes\",\n  -1 * (avg(rx_bytes) - lag(avg(rx_bytes)) OVER (PARTITION BY container_name ORDER BY \"time\")) AS \"rx_bytes\",\n  container_name as docker\nFROM docker_container_net\nWHERE\n  $__timeFilter(\"time\") AND container_name in($docker)\nGROUP BY time, container_name\nORDER BY time ASC\n"
    }
   ]
  },
  {
   "title": "DISK",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "rawSql": "SELECT\n  \"time\" AS \"time\",\n  avg(io_service_bytes_recursive_read) - lag(avg(io_service_bytes_recursive_read)) OVER (PARTITION BY container_name ORDER BY \"time\") AS \"read\",\n  -1 * (avg(io_service_bytes_recursive_write) - lag(avg(io_service_bytes_recursive_write)) OVER (PARTITION BY container_name ORDER BY \"time\")) AS \"write\",\n  container_name as docker\nFROM docker_container_blkio\nWHERE\n  $__timeFilter(\"time\") AND container_name in($docker)\nGROUP BY time, container_name\nORDER BY time ASC\n"
    }
   ]
  }
 ]
}